#   https://projecteuler.net/problem=2
#   Each new term in the Fibonacci sequence is generated by adding the previous two terms.
#   By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#   By considering the terms in the Fibonacci sequence whose values do not exceed four million,
#   find the sum of the even-valued terms.

#   Because visualization is a key strength of R, we're gonna do some extra schtuff.
#   We will visualize the proportion of even to odd Fibonacci numbers, as well as the convergence of the ratio of growth
#   between consecutive Fibonacci numbers toward the golden ratio 1.618


count_even <- 1         # count the even Fibonacci numbers
count_odd <- 1          # count the odd Fibonacci numbers
ratios <- numeric()     # list of ratios to track the growth
total <- 0              # sum of all even Fibonacci numbers below the limit

i <- 1                  # F_n
j <- 2                  # F_(n+1)
k <- 0                  # temporary variable for easy iteration through the sequence

index <- 1              # index counter for ratios list

while (i < 4 * 10^6) {                      # while the nth Fibonacci number is less than the limit
  if (i %% 2 == 0) {                        # if the nth Fibonacci number is even
    count_even <- count_even + 1            # increment the even count
    total <- total + i                      # add it to our total
  }
  else { count_odd <- count_odd + 1 }       # if the nth Fibonacci number is odd, increment the odd count

  ratios[index] <- j / i                    # record the ratio
  index <- index + 1                        # increment the ratio list counter

  k <- i                                    # calculate the next pair of Fibonacci numbers
  i <- j
  j <- j + k
}

print(total)

library(ggplot2)  # load a visualization library

count_data <- data.frame(             # a data frame is a tabular structure
  type = c("Even", "Odd"),            # create a column in the data frame named `type` with the values "Even" and "Odd"
  count = c(count_even, count_odd)    # create a column in the data frame named `count` with the respective count values
)

# ggplot() initializes a ggplot object with the count_data data frame
# aes() map the x-axis to `type`, the y-axis to `count` and use the `type` column to determine the fill color
# geom_bar() adds a bar plot to the ggplot object
# stat = "identity" specifies that we want to use the actual values in the `count` column
# labs() gives labels to the plot
# theme_minimal() applies a simple theme to the plot
ggplot(count_data, aes(x = type, y = count, fill = type)) +
  geom_bar(stat = "identity") +
  labs(title = "Proportion of Even vs. Odd Fibonacci Numbers",
       x = "Parity",
       y = "Count") +
  theme_minimal()

ratio_data <- data.frame(
  n = seq_along(ratios),    # seq_along(ratios) generates a sequence from 1 to the length of `ratios`
  ratio = ratios            # create a column `ratio` populated with the data from the `ratios` vector
)

ggplot(ratio_data, aes(x = n, y = ratio)) +
  geom_line(color = "blue") +
  geom_hline(yintercept = 1.618, linetype = "dashed", color = "red") +
  labs(title = "Convergence of Fibonacci Ratios to the Golden Ratio",
       x = "nth Fibonacci Number",
       y = "Ratio of Consecutive Fibonacci Numbers") +
  theme_minimal()
